query GenerateAvdDeviceInputsQuery($name: String!) {
  DcimFabricSwitch(name__value: $name) {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        role {
          value
        }
        evpn_gateway_group {
          node {
            __typename
            id
            display_label
            name {
              value
            }
            resiliency_model {
              value
            }
            evpn_l2_enabled {
              value
            }
            evpn_l3_enabled {
              value
            }
            evpn_l3_inter_domain {
              value
            }
            d_path_enabled {
              value
            }
            all_active_multihoming_enabled {
              value
            }
            ethernet_segment_identifier {
              value
            }
            ethernet_segment_rt_import {
              value
            }
            local_domain {
              node {
                __typename
                id
                display_label
                domain_id {
                  value
                }
                fabric {
                  node {
                    __typename
                    id
                    name {
                      value
                    }
                  }
                }
              }
            }
            pod {
              node {
                __typename
                id
                name {
                  value
                }
                evpn_domain {
                  node {
                    __typename
                    id
                    display_label
                    domain_id {
                      value
                    }
                    fabric {
                      node {
                        __typename
                        id
                        name {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
            members {
              edges {
                node {
                  __typename
                  id
                  name {
                    value
                  }
                  role {
                    value
                  }
                  pod {
                    node {
                      __typename
                      id
                      name {
                        value
                      }
                    }
                  }
                }
              }
            }
            remote_domain {
              node {
                __typename
                id
                display_label
                domain_id {
                  value
                }
                fabric {
                  node {
                    __typename
                    id
                    name {
                      value
                    }
                  }
                }
                remote_gateway_groups {
                  edges {
                    node {
                      __typename
                      id
                      display_label
                      name {
                        value
                      }
                      local_domain {
                        node {
                          __typename
                          id
                          display_label
                          domain_id {
                            value
                          }
                          fabric {
                            node {
                              __typename
                              id
                              name {
                                value
                              }
                            }
                          }
                        }
                      }
                      pod {
                        node {
                          __typename
                          id
                          name {
                            value
                          }
                          evpn_domain {
                            node {
                              __typename
                              id
                              display_label
                              domain_id {
                                value
                              }
                              fabric {
                                node {
                                  __typename
                                  id
                                  name {
                                    value
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                      members {
                        edges {
                          node {
                            __typename
                            id
                            name {
                              value
                            }
                            role {
                              value
                            }
                            pod {
                              node {
                                __typename
                                id
                                name {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        asn {
          node {
            asn {
              value
            }
          }
        }
        node_id {
          value
        }
        avd_custom_hostvars {
          value
        }
        loopback_ip {
          node {
            __typename
            id
            address {
              value
            }
            ip_prefix {
              node {
                __typename
                prefix {
                  value
                }
              }
            }
          }
        }
        vtep_loopback_ip {
          node {
            __typename
            id
            address {
              value
            }
            ip_prefix {
              node {
                __typename
                prefix {
                  value
                }
              }
            }
          }
        }
        mgmt_ip {
          node {
            __typename
            id
            address {
              value
            }
          }
        }
        mlag_domain {
          node {
            __typename
            id
            domain_id {
              value
            }
            asn {
              node {
                asn {
                  value
                }
              }
            }
            virtual_router_mac {
              value
            }
            peers {
              edges {
                node {
                  __typename
                  id
                  name {
                    value
                  }
                }
              }
            }
          }
        }
        rack {
          node {
            __typename
            id
            name {
              value
            }
            mlag {
              value
            }
            devices {
              edges {
                node {
                  __typename
                  id
                  ... on DcimFabricSwitch {
                    name {
                      value
                    }
                    role {
                      value
                    }
                  }
                }
              }
            }
          }
        }
        pod {
          node {
            id
            name {
              value
            }
            pod_ip_pools {
              edges {
                node {
                  __typename
                  id
                  ... on CoreIPAddressPool {
                    name {
                      value
                    }
                    resources {
                      edges {
                        node {
                          __typename
                          ... on IpamPrefix {
                            prefix {
                              value
                            }
                            role {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                  ... on CoreIPPrefixPool {
                    name {
                      value
                    }
                    resources {
                      edges {
                        node {
                          __typename
                          ... on IpamPrefix {
                            prefix {
                              value
                            }
                            role {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            mlag_peer_pool {
              node {
                id
                name {
                  value
                }
              }
            }
            mlag_l3_pool {
              node {
                id
                name {
                  value
                }
              }
            }
            racks {
              edges {
                node {
                  id
                  mlag {
                    value
                  }
                }
              }
            }
            avd_custom_hostvars {
              value
            }
            parent {
              node {
                __typename
                  id
                  name {
                    value
                  }
                  ... on NetworkFabric {
                    children {
                      edges {
                        node {
                          __typename
                          id
                          ... on NetworkPod {
                            devices {
                              edges {
                                node {
                                  __typename
                                  id
                                  ... on DcimFabricSwitch {
                                    name {
                                      value
                                    }
                                    role {
                                      value
                                    }
                                    node_id {
                                      value
                                    }
                                    interfaces {
                                      edges {
                                        node {
                                          __typename
                                          id
                                          ... on InterfacePhysical {
                                            name {
                                              value
                                            }
                                            role {
                                              value
                                            }
                                            connector {
                                              node {
                                                __typename
                                                id
                                                connected_endpoints {
                                                  edges {
                                                    node {
                                                      __typename
                                                      id
                                                      ... on DcimInterface {
                                                        name {
                                                          value
                                                        }
                                                        device {
                                                          node {
                                                            __typename
                                                            id
                                                            name {
                                                              value
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                    mgmt_gateway {
                      value
                    }
                  mgmt_routes {
                    value
                  }
                  virtual_router_mac {
                    value
                  }
                  underlay_routing_protocol {
                    value
                  }
                  overlay_routing_protocol {
                    value
                  }
                  evpn_vlan_aware_bundles {
                    value
                  }
                  p2p_uplinks_mtu {
                    value
                  }
                  uplink_pool {
                    node {
                      id
                      name {
                        value
                      }
                      default_prefix_length {
                        value
                      }
                    }
                  }
                  fabric_ip_pools {
                    edges {
                      node {
                        __typename
                        id
                        ... on CoreIPAddressPool {
                          name {
                            value
                          }
                          resources {
                            edges {
                              node {
                                __typename
                                ... on IpamPrefix {
                                  prefix {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                }
                              }
                            }
                          }
                        }
                        ... on CoreIPPrefixPool {
                          name {
                            value
                          }
                          resources {
                            edges {
                              node {
                                __typename
                                ... on IpamPrefix {
                                  prefix {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                  vtep_pool {
                    node {
                      id
                      name {
                        value
                      }
                      default_prefix_length {
                        value
                      }
                    }
                  }
                  loopback_pool {
                    node {
                      id
                      name {
                        value
                      }
                      default_prefix_length {
                        value
                      }
                    }
                  }
                  spanning_tree_mode {
                    value
                  }
                  spanning_tree_priorities {
                    edges {
                      node {
                        role {
                          value
                        }
                        priority {
                          value
                        }
                      }
                    }
                  }
                  bgp_evpn_overlay_password {
                    value
                  }
                  bgp_underlay_password {
                    value
                  }
                  bgp_mlag_password {
                    value
                  }
                  avd_custom_hostvars {
                    value
                  }
                  dns_servers {
                    edges {
                      node {
                        name { value }
                        ip_address { value }
                        vrf { value }
                      }
                    }
                  }
                  ntp_servers {
                    edges {
                      node {
                        name { value }
                        server_vrf { value }
                        iburst { value }
                      }
                    }
                  }
                  local_users {
                    edges {
                      node {
                        name { value }
                        privilege { value }
                        role { value }
                        password_type { value }
                        password { value }
                      }
                    }
                  }
                  avd_evpn {
                    node {
                      __typename
                      ebgp_multihop {
                        value
                      }
                      overlay_bgp_rtc {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              id
              ... on InterfacePhysical {
                name {
                  value
                }
                role {
                  value
                }
                spanning_tree_portfast {
                  value
                }
                spanning_tree_bpduguard {
                  value
                }
                description {
                  value
                }
                tagged_vlan {
                  edges {
                    node {
                      __typename
                      vlan_id {
                        value
                      }
                      status {
                        value
                      }
                    }
                  }
                }
                untagged_vlan {
                  node {
                    __typename
                    vlan_id {
                      value
                    }
                    status {
                      value
                    }
                  }
                }
                lag {
                  node {
                    __typename
                    id
                    name {
                      value
                    }
                    ... on InterfaceLag {
                      channel_id {
                        value
                      }
                      lacp_mode {
                        value
                      }
                      evpn_ethernet_segment {
                        value
                      }
                      tagged_vlan {
                        edges {
                          node {
                            __typename
                            vlan_id {
                              value
                            }
                            status {
                              value
                            }
                          }
                        }
                      }
                      untagged_vlan {
                        node {
                          __typename
                          vlan_id {
                            value
                          }
                          status {
                            value
                          }
                        }
                      }
                    }
                  }
                }
                connector {
                  node {
                    __typename
                    id
                    connected_endpoints {
                      edges {
                        node {
                          __typename
                          id
                          ... on DcimInterface {
                            name {
                              value
                            }
                            device {
                              node {
                                __typename
                                id
                                name {
                                  value
                                }
                                ... on DcimFabricSwitch {
                                  role {
                                    value
                                  }
                                }
                              }
                            }
                          }
                          ... on InterfacePhysical {
                            lag {
                              node {
                                __typename
                                id
                                name {
                                  value
                                }
                                ... on InterfaceLag {
                                  channel_id {
                                    value
                                  }
                                  lacp_mode {
                                    value
                                  }
                                  evpn_ethernet_segment {
                                    value
                                  }
                                  tagged_vlan {
                                    edges {
                                      node {
                                        __typename
                                        vlan_id {
                                          value
                                        }
                                        status {
                                          value
                                        }
                                      }
                                    }
                                  }
                                  untagged_vlan {
                                    node {
                                      __typename
                                      vlan_id {
                                        value
                                      }
                                      status {
                                        value
                                      }
                                    }
                                  }
                                  lag_members {
                                    edges {
                                      node {
                                        __typename
                                        id
                                        name {
                                          value
                                        }
                                        connector {
                                          node {
                                            __typename
                                            id
                                            connected_endpoints {
                                              edges {
                                                node {
                                                  __typename
                                                  id
                                                  ... on InterfacePhysical {
                                                    name {
                                                      value
                                                    }
                                                    role {
                                                      value
                                                    }
                                                    spanning_tree_portfast {
                                                      value
                                                    }
                                                    spanning_tree_bpduguard {
                                                      value
                                                    }
                                                    description {
                                                      value
                                                    }
                                                    lag {
                                                      node {
                                                        __typename
                                                        id
                                                        name {
                                                          value
                                                        }
                                                        ... on InterfaceLag {
                                                          channel_id {
                                                            value
                                                          }
                                                          lacp_mode {
                                                            value
                                                          }
                                                          evpn_ethernet_segment {
                                                            value
                                                          }
                                                          tagged_vlan {
                                                            edges {
                                                              node {
                                                                __typename
                                                                vlan_id {
                                                                  value
                                                                }
                                                                status {
                                                                  value
                                                                }
                                                              }
                                                            }
                                                          }
                                                          untagged_vlan {
                                                            node {
                                                              __typename
                                                              vlan_id {
                                                                value
                                                              }
                                                              status {
                                                                value
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                    tagged_vlan {
                                                      edges {
                                                        node {
                                                          __typename
                                                          vlan_id {
                                                            value
                                                          }
                                                          status {
                                                            value
                                                          }
                                                        }
                                                      }
                                                    }
                                                    untagged_vlan {
                                                      node {
                                                        __typename
                                                        vlan_id {
                                                          value
                                                        }
                                                        status {
                                                          value
                                                        }
                                                      }
                                                    }
                                                    device {
                                                      node {
                                                        __typename
                                                        id
                                                        name {
                                                          value
                                                        }
                                                        ... on DcimFabricSwitch {
                                                          role {
                                                            value
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  NetworkLink(role__value: "dci") {
    edges {
      node {
        __typename
        id
        display_label
        name {
          value
        }
        role {
          value
        }
        include_in_underlay_protocol {
          value
        }
        connected_endpoints {
          edges {
            node {
              __typename
              id
              ... on InterfacePhysical {
                name {
                  value
                }
                role {
                  value
                }
                device {
                  node {
                    __typename
                    id
                    name {
                      value
                    }
                    ... on DcimFabricSwitch {
                      role {
                        value
                      }
                      asn {
                        node {
                          asn {
                            value
                          }
                        }
                      }
                      pod {
                        node {
                          parent {
                            node {
                              __typename
                              id
                              ... on NetworkFabric {
                                name {
                                  value
                                }
                                dci_pool {
                                  node {
                                    id
                                    name {
                                      value
                                    }
                                    default_prefix_length {
                                      value
                                    }
                                  }
                                }
                                fabric_ip_pools {
                                  edges {
                                    node {
                                      __typename
                                      id
                                      ... on CoreIPPrefixPool {
                                        name {
                                          value
                                        }
                                        resources {
                                          edges {
                                            node {
                                              __typename
                                              ... on IpamPrefix {
                                                prefix {
                                                  value
                                                }
                                                role {
                                                  value
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
