query GenerateAvdInputsQuery($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        children {
          edges {
            node {
              __typename
              ... on NetworkPod {
                __typename
                racks {
                  edges {
                    node {
                      __typename
                      devices {
                        edges {
                          node {
                            __typename
                            id
                            ... on DcimFabricSwitch {
                              name {
                                value
                              }
                              avd_artifact {
                                node {
                                  __typename
                                  hostvar_file {
                                    node {
                                      id
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                devices {
                  edges {
                    node {
                      __typename
                      id
                      name {
                        value
                      }
                      avd_artifact {
                        node {
                          __typename
                          hostvar_file {
                            node {
                              id
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
