query AvdDeviceConfigQuery($name: String!) {
  DcimFabricSwitch(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        avd_artifact {
          node {
            id
            structured_config_file {
              node {
                id
                checksum {
                  value
                }
              }
            }
          }
        }
      }
    }
  }
}
