query AvdAntaCatalogQuery($name: String!) {
  target: DcimFabricSwitch(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        pod {
          node {
            id
            parent {
              node {
                __typename
                id
                ... on NetworkFabric {
                  name {
                    value
                  }
                  anta_enabled {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  DcimFabricSwitch {
    edges {
      node {
        id
        name {
          value
        }
        pod {
          node {
            id
            parent {
              node {
                __typename
                id
              }
            }
          }
        }
        avd_artifact {
          node {
            id
            structured_config_file {
              node {
                id
              }
            }
          }
        }
      }
    }
  }
}
