query ComputedInterfaceDescriptionQuery($id: ID!) {
  DcimInterface(ids: [$id]) {
    edges {
      node {
        __typename
        id
        ... on DcimEndpoint {
          __typename
          connector {
            node {
              __typename
              id
              connected_endpoints {
                edges {
                  node {
                    __typename
                    id
                    ... on DcimInterface {
                      __typename
                      name {
                        value
                      }
                      device {
                        node {
                          __typename
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
