query ContainerLabTopology($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        name {
          value
        }
        children {
          edges {
            node {
              __typename
              ... on NetworkPod {
                devices {
                  edges {
                    node {
                      __typename
                      ... on DcimFabricSwitch {
                        id
                        name {
                          value
                        }
                        role {
                          value
                        }
                        device_type {
                          node {
                            name {
                              value
                            }
                            containerlab_interface_mapping {
                              value
                            }
                            platform {
                              node {
                                containerlab_os {
                                  value
                                }
                                containerlab_image {
                                  value
                                }
                              }
                            }
                          }
                        }
                        platform {
                          node {
                            containerlab_os {
                              value
                            }
                            containerlab_image {
                              value
                            }
                          }
                        }
                        mgmt_ip {
                          node {
                            ... on IpamIPAddress {
                              address {
                                value
                              }
                            }
                          }
                        }
                        interfaces {
                          edges {
                            node {
                              __typename
                              ... on DcimEndpoint {
                                connector {
                                  node {
                                    id
                                    ... on NetworkLink {
                                      role {
                                        value
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                racks {
                  edges {
                    node {
                      name {
                        value
                      }
                      devices {
                        edges {
                          node {
                            __typename
                            ... on DcimFabricSwitch {
                              id
                              name {
                                value
                              }
                              role {
                                value
                              }
                              device_type {
                                node {
                                  name {
                                    value
                                  }
                                  containerlab_interface_mapping {
                                    value
                                  }
                                  platform {
                                    node {
                                      containerlab_os {
                                        value
                                      }
                                      containerlab_image {
                                        value
                                      }
                                    }
                                  }
                                }
                              }
                              platform {
                                node {
                                  containerlab_os {
                                    value
                                  }
                                  containerlab_image {
                                    value
                                  }
                                }
                              }
                              mgmt_ip {
                                node {
                                  ... on IpamIPAddress {
                                    address {
                                      value
                                    }
                                  }
                                }
                              }
                              interfaces {
                                edges {
                                  node {
                                    __typename
                                    ... on DcimEndpoint {
                                      connector {
                                        node {
                                          id
                                          ... on NetworkLink {
                                            role {
                                              value
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  ComputePhysicalServer {
    edges {
      node {
        __typename
        id
        name {
          value
        }
        rack {
          node {
            name {
              value
            }
          }
        }
        platform {
          node {
            containerlab_os {
              value
            }
            containerlab_image {
              value
            }
          }
        }
        primary_address {
          node {
            ... on IpamIPAddress {
              address {
                value
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              ... on DcimEndpoint {
                connector {
                  node {
                    id
                    ... on NetworkLink {
                      role {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
