"""Write the catalogue entries for the static sites from the HTML under ``sites/``.

``otternet-shop`` and ``otternet-wiki`` are nginx applications whose pages are
the files in ``sites/shop`` and ``sites/wiki``. Their catalogue entries carry
those files inside ``default_values``, so the entries are generated: edit the
HTML, run this script, and commit both. ``tests/unit/test_site_catalogue_entries.py``
fails when the entries and the HTML differ.

    uv run python scripts/render_site_entries.py
"""

from __future__ import annotations

from itertools import starmap
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parent.parent
CATALOGUE = REPO / "objects" / "35a_otternet_app_catalogue.yml"
SITES = REPO / "sites"
BEGIN = "    # BEGIN generated by scripts/render_site_entries.py -- do not edit by hand\n"
END = "    # END generated by scripts/render_site_entries.py\n"

# name, title, description, source directory, whether the shared stylesheet is a file of the site
ENTRIES = [
    (
        "otternet-shop",
        "OTTERNET shop",
        "A one-page shop front served by nginx, showing the network path to it",
        "shop",
        False,
    ),
    (
        "otternet-wiki",
        "OTTERNET wiki",
        "A small wiki of static pages served by nginx: how to request an application, services, glossary, changelog",
        "wiki",
        True,
    ),
]

HEADER = """    # Static web sites, served by nginx. The pages are the files under sites/, carried in
    # `default_values` as a ConfigMap that the chart mounts over nginx's document root, so
    # changing a page is a catalogue edit and needs no image build. `bjw-s/app-template` is a
    # generic chart that runs any image from values. The image is the unprivileged nginx, which
    # listens on 8080, so the Service publishes 80 (`junos-http`) and targets 8080. This chart's
    # Service takes labels under `service.main.labels`, and `externalTrafficPolicy` is set here
    # because the chart is not in crossplane_fabric_app's known-chart map and an unknown chart
    # must say `Local` itself. A running application keeps the pages it was pinned with.
    # The lines are long because they are HTML.
    # yamllint disable rule:line-length
"""
FOOTER = "    # yamllint enable rule:line-length\n"


class _Dumper(yaml.SafeDumper):
    pass


def _str(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|" if "\n" in value else None)


_Dumper.add_representer(str, _str)


def site_files(directory: str, with_css: bool) -> dict[str, str]:
    files = {p.name: p.read_text(encoding="utf-8") for p in sorted((SITES / directory).glob("*.html"))}
    if with_css:
        files["otternet.css"] = (SITES / "_shared" / "otternet.css").read_text(encoding="utf-8")
    return files


def values_for(directory: str, with_css: bool) -> dict[str, Any]:
    return {
        "controllers": {
            "main": {
                "replicas": 2,
                "containers": {
                    "main": {"image": {"repository": "docker.io/nginxinc/nginx-unprivileged", "tag": "1.29-alpine"}}
                },
            }
        },
        "service": {
            "main": {
                "controller": "main",
                "type": "LoadBalancer",
                "externalTrafficPolicy": "Local",
                "labels": {"otternet.lab/advertise": "true"},
                "ports": {"http": {"port": 80, "targetPort": 8080}},
            }
        },
        "configMaps": {"site": {"data": site_files(directory, with_css)}},
        "persistence": {
            "site": {
                "type": "configMap",
                "identifier": "site",
                "globalMounts": [{"path": "/usr/share/nginx/html", "readOnly": True}],
            }
        },
    }


def values_text(directory: str, with_css: bool) -> str:
    return yaml.dump(values_for(directory, with_css), Dumper=_Dumper, sort_keys=False, width=10_000, allow_unicode=True)


def entry_text(name: str, title: str, description: str, directory: str, with_css: bool) -> str:
    values = "".join(
        f"        {line}\n" if line.strip() else "\n" for line in values_text(directory, with_css).splitlines()
    )
    return (
        f"    - name: {name}\n"
        f'      title: "{title}"\n'
        f'      description: "{description}"\n'
        "      status: active\n"
        "      requestable: true\n"
        "      chart_repository: https://bjw-s-labs.github.io/helm-charts\n"
        "      chart_name: app-template\n"
        '      chart_version: "5.2.1"\n'
        "      default_vip_block_size: 28\n"
        "      default_service_selector:\n"
        '        - "otternet.lab/advertise=true"\n'
        "      default_advertised_services:\n"
        "        - junos-http\n"
        "      default_values: |\n"
        f"{values}"
    )


def generated_block() -> str:
    entries = "\n".join(starmap(entry_text, ENTRIES))
    return f"{BEGIN}{HEADER}{entries}{FOOTER}{END}"


def render(text: str) -> str:
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + generated_block() + text[end:]


if __name__ == "__main__":
    current = CATALOGUE.read_text(encoding="utf-8")
    CATALOGUE.write_text(render(current), encoding="utf-8")
    print("rewrote", CATALOGUE)
