"""Zone advertisement consistency check.

Cycle 032 gave `SecurityZone` the fabric side of a zone -- the prefix list
governing what the DC advertises toward it, and the switch that applies it --
and cycle 033 made an approved grant write its VIP into that list. Both rest on
a reference nothing enforces.

**The prefix list is a NAME, not a relationship, and that was forced.** There
are zero `RoutingPrefixList` objects in this graph: every prefix list in this
fabric lives inside `avd_custom_hostvars` as an entry in
`custom_structured_configuration_prefix_lists`, which is AVD's channel for
inputs this data model does not model. A relationship needs a peer to point at
and there is none. Cycle 032 accepted that on one condition -- that the mismatch
be *detectable* -- and this is the check that discharges it.

FOUR RULES, and every one of them describes a failure that is silent today.

* **A zone names a prefix list nothing defines.** The generator writes an entry
  into a list no route map matches, the route never appears, and nothing
  errors. The name is checked against fabric scope and the advertising device's
  own scope, because either may declare it.
* **A zone carries one half of the policy and not the other.** The schema
  permits it; the generator raises on it at run time, which is late. Here it
  blocks the merge that introduced it.
* **An approved grant's VIP sits outside its application's `vip_block`.** The
  cluster only ever advertises addresses from that block, so the firewall
  permits a session to an address the fabric will never carry: permitted and
  unroutable, which is exactly what
  `schemas/service/access_services.yml` warns about on `destination_vip`.
* **An approved grant names an application that is not exposed.** An unexposed
  application gets no pool, no VIP and no advertisement -- the schema comment
  on `exposed` says so -- so the grant cannot work however correct everything
  else is.

WHAT THIS DELIBERATELY DOES NOT CHECK. Whether the rendered configuration on the
border leaf actually contains the sequence. That lives in an artifact rather
than in the graph, it is regenerated by a chain that runs explicitly, and a
check that read it would fail for hours at a time purely because nobody had run
`invoke avd` yet. Blocking merges on a stale artifact would train people to
ignore the check.

GLOBAL, with no `targets`. These are statements about the whole graph -- "some
zone names a list nobody declares" has no natural group to iterate -- exactly
like `peering-consistency` beside it.
"""

from __future__ import annotations

from dataclasses import dataclass
from ipaddress import ip_address, ip_network
from typing import Any

from infrahub_sdk.checks import InfrahubCheck

from .zone_advertisement_check_query import ZoneAdvertisementCheckQuery

KIND_ZONE = "SecurityZone"
KIND_GRANT = "ServiceAppAccess"

# The key inside avd_custom_hostvars that declares prefix lists. Named once so
# the check and generate_app_access.py cannot drift about where they look.
PREFIX_LISTS_KEY = "custom_structured_configuration_prefix_lists"


@dataclass(frozen=True)
class Finding:
    """One violation, with everything needed to attribute it in the UI."""

    message: str
    object_id: str
    object_type: str


def _value(wrapper: Any) -> Any:
    return wrapper.value if wrapper is not None else None


def _node_of(relationship: Any) -> Any:
    return relationship.node if relationship is not None else None


def _edges_of(relationship: Any) -> list[Any]:
    if relationship is None:
        return []
    return [edge.node for edge in relationship.edges if edge.node is not None]


def declared_prefix_lists(hostvars: Any) -> set[str]:
    """Prefix-list names declared in one `avd_custom_hostvars` blob.

    Defensive about shape on purpose: the attribute is free-form JSON that a
    human edits, so a malformed blob must make this check report nothing rather
    than raise and take the whole proposed change down with it.
    """
    if not isinstance(hostvars, dict):
        return set()
    entries = hostvars.get(PREFIX_LISTS_KEY)
    if not isinstance(entries, list):
        return set()
    return {entry["name"] for entry in entries if isinstance(entry, dict) and isinstance(entry.get("name"), str)}


def check_zone_policies(parsed: ZoneAdvertisementCheckQuery) -> list[Finding]:
    """Rules 1 and 2: the zone's own advertisement policy."""
    findings: list[Finding] = []

    fabric_declared: set[str] = set()
    for fabric in _edges_of(parsed.network_fabric):
        fabric_declared |= declared_prefix_lists(_value(fabric.avd_custom_hostvars))

    for zone in _edges_of(parsed.security_zone):
        name = _value(zone.name)
        prefix_list = _value(zone.dc_advertised_prefix_list)
        device = _node_of(zone.advertising_device)

        # Neither half: the DC advertises nothing toward this zone, which is the
        # steady state for four of the six and is not a finding.
        if prefix_list is None and device is None:
            continue

        if prefix_list is None or device is None:
            missing = "advertising_device" if device is None else "dc_advertised_prefix_list"
            findings.append(
                Finding(
                    message=(
                        f"Zone {name!r} carries one half of its advertisement policy and not the other "
                        f"({missing} is unset). A grant from this zone will fail when the generator runs."
                    ),
                    object_id=zone.id,
                    object_type=KIND_ZONE,
                )
            )
            continue

        declared = fabric_declared | declared_prefix_lists(_value(device.avd_custom_hostvars))
        if prefix_list not in declared:
            findings.append(
                Finding(
                    message=(
                        f"Zone {name!r} advertises through prefix list {prefix_list!r}, which neither the "
                        f"fabric nor {_value(device.name)!r} declares. A grant would add a permit to a list "
                        "no route map matches: the route never appears and nothing errors."
                    ),
                    object_id=zone.id,
                    object_type=KIND_ZONE,
                )
            )

    return findings


def check_grant_reachability(parsed: ZoneAdvertisementCheckQuery) -> list[Finding]:
    """Rules 3 and 4: an approved grant the fabric can never carry."""
    findings: list[Finding] = []

    for grant in _edges_of(parsed.service_app_access):
        if not _value(grant.approved):
            continue

        name = _value(grant.name)
        application = _node_of(grant.application)
        if application is None:
            continue

        if not _value(application.exposed):
            findings.append(
                Finding(
                    message=(
                        f"Grant {name!r} names application {_value(application.name)!r}, which is not exposed. "
                        "An unexposed application gets no pool, no VIP and no advertisement, so the firewall "
                        "would permit a session to an address that is never reachable."
                    ),
                    object_id=grant.id,
                    object_type=KIND_GRANT,
                )
            )
            continue

        block = _node_of(application.vip_block)
        vip = _node_of(grant.destination_vip)
        if block is None or vip is None:
            continue

        block_value = _value(block.prefix)
        vip_value = _value(vip.address)
        if block_value is None or vip_value is None:
            continue

        try:
            inside = ip_address(vip_value.split("/")[0]) in ip_network(block_value)
        except ValueError:
            # A malformed address is a different defect and a different check's
            # business; reporting it here would attribute it to the wrong thing.
            continue

        if not inside:
            findings.append(
                Finding(
                    message=(
                        f"Grant {name!r} points at {vip_value}, which is outside "
                        f"{_value(application.name)!r}'s VIP block {block_value}. The cluster only advertises "
                        "addresses from that block, so the session is permitted and unroutable."
                    ),
                    object_id=grant.id,
                    object_type=KIND_GRANT,
                )
            )

    return findings


def collect_findings(parsed: ZoneAdvertisementCheckQuery) -> list[Finding]:
    return check_zone_policies(parsed) + check_grant_reachability(parsed)


class ZoneAdvertisementCheck(InfrahubCheck):
    """Refuse a proposed change whose advertisement policy cannot work."""

    query = "zone_advertisement_check"

    def validate(self, data: dict) -> None:  # type: ignore[override]
        """Emit every finding. Any log_error blocks the merge."""
        parsed = ZoneAdvertisementCheckQuery(**data)
        findings = collect_findings(parsed)

        for finding in findings:
            self.log_error(
                message=finding.message,
                object_id=finding.object_id,
                object_type=finding.object_type,
            )

        if not findings:
            # Says what was examined, not merely that nothing was wrong. A check
            # that reports success over an empty collection manufactures
            # confidence, which is the failure `peering_consistency_check`
            # documents at length.
            zones = len(_edges_of(parsed.security_zone))
            grants = len(_edges_of(parsed.service_app_access))
            self.log_info(message=f"Advertisement policy is consistent across {zones} zone(s) and {grants} grant(s)")
